name: Documentation Build and Publish
on:
  push:
    branches:
      - main
      - test/**
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Deploy docs
      uses: mhausenblas/mkdocs-deploy-gh-pages@master
      env:
        GITHUB_TOKEN: ${{ github.token }}
